modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
showAsResourcePack=false

[[mods]]
  modId="musictriggers"
  version="${version}"
  displayName="Music Triggers"
  updateJSONURL=""
  displayURL="https://www.curseforge.com/minecraft/mc-mods/music-triggers"
  logoFile="musictriggers_logo.png"
  authors="The_Computerizer"
  description='''
  Lets you play music based on in game triggers
  '''

  [[dependencies.musictriggers]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.musictriggers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.musictriggers]]
    modId="theimpossiblelibrary"
    mandatory=true
    versionRange="[1.16.5-0.2.3,)"
    ordering="NONE"
    side="BOTH"